### ISSUE TITLE
Render rich text editor

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#722] opened 2024-10-15 18:26 UTC
## Motivation
- So users can edit in rich text

## Requirements 
- In the form builder and default form editor, rich text fields render the prosemirror editor
- Support for support only non-child/non-parent fields for now (e.g. bold, italic, links, etc.)

## Acceptance Criteria
- "Design" for the rich text input can be extremely basic at this point, more or less porting what Travis has already with few modifications (less the ability to change stylesheets. We can use just one default stylesheet.)
- Acceptable if the editor still includes all options travis demo'd but they just don't work, e.g. provides stubs for functions that request fields/pub types/attributes/etc.

**Comment by allisonking** [comment] 2024-10-22 20:37
### Approach
I'm making as few changes as possible within the `context-editor` package. I did have to add a simple `index.ts` in order for preconstruct to build the editor as a package that I could import elsewhere.

* I'm working on a separate branch https://github.com/pubpub/platform/tree/aking/722/import-richtext-editor which is the latest `main` with Travis' context editor branch merged in. The diff is tough because the editor branch is behind main, but you can see my changes [here](https://github.com/pubpub/platform/compare/main...aking/722/import-richtext-editor) and then click my commits at the bottom

### Log

1. Merging the two branches seems to break storybook for some reason. I thought it might be because we have, since the branch was branched, added our own storybook, so there might be different versions of storybook. I'm not sure though, but this does seem to be contained to storybook from what I can tell
![Image](https://github.com/user-attachments/assets/2b1b46e1-730b-48a8-999f-cdcbc31bb051)

3. We'll need to pass some sort of `getPubs` that can filter by a string. I've mocked this out for now, not sure how we would pass a server call with a filter to a client component?
4. `getByPubId` not used yet, though it's a required prop. leaving it out for now!
5. There are some logs about `window` not being defined which I'm guessing is because we are using the component in an app with server side rendering, not quite sure the right way to work around this
6. There are parts of the editor that are hard coded to use the `rd` community, so for now I'm making a local `rd` community just to smooth things along.
  * For example, getting the name of the pub is hard coded in the context editor as `rd:title` right now, probably need to use something like [`getPubTitle`](https://github.com/pubpub/platform/blob/main/core/lib/pubs.ts#L7)

7. The pop up menu renders kind of far away from the cursor here, but not in storybook

For now, things kind of work!
![Image](https://github.com/user-attachments/assets/79f09821-c60b-4c31-ab3b-ec7e38b3cd34)
![Image](https://github.com/user-attachments/assets/9cb89cc8-6277-438b-b074-3f47be19ed64)

### Next steps

We won't want to merge this branch since right now it creates a page at `/c/{community}/test` to render the editor. Also, it contains Travis' editor code which I think he still wanted to clean up. Some next steps might be:

* Merge the latest `main` into Travis' branch 
  * Might take some effort to get storybook working again
* Figure out the various server related issues (3‍⃣ and 5‍⃣ above)
* There are some types we can define more strictly in the context editor to help with integration
* Write a basic unit test to show the editor rendering and then remove the test page

**Comment by tefkah** [comment] 2024-10-23 11:50
Great writeup Allison!

Some comments:

1. For Storybook, the problem is probably that we switched to using `verbatimModuleSyntax`, meaning that you have to import types using `import type { PanelProps }` rather than doing `import { PanelProps }`. My guess is that Storybook (or vite) honors that setting in tsconfig, otherwise I'm not sure why it worked before. In any case, I fixed this in this branch if you're curious! https://github.com/pubpub/platform/tree/tfk/722

**Comment by allisonking** [comment] 2024-10-23 14:10
Oh yay, thanks so much for getting storybook working!! 

> I don't think you need to figure out 3️⃣, (i think you maybe meant 2️⃣? I will figure that out!). If we can get the editor to display things while not having to figure out 5️⃣ that would be best, we can figure that out later with the editor already more integrated in main.

oops, off by one error... I meant 2️⃣ and 4️⃣ ! Sounds like you know what to do with 2️⃣ and 4️⃣ should be an easy fix by dynamically importing, so we should be good there 👍 

> Any examples of stricter types? I love stricter typing haha, so I'm all for it. Currently the package doesn't pass tsc, so we need to figure out some way to fix that or just ignore it for now.

Yes! So the prop definition for `ContextEditor` is pretty loose right now (understandably!). `pubTypes` should maybe use something like `GetPubTypesResult` tho that's only defined in core right now. Same with `getPubs` (sounds like maybe we can pull a type from `/site` API perhaps?). Or the editor should maybe define just the fields it needs (for instance, `pubTypes` expects `id`, but also to have nested `fields` that have a `name`. And maybe other stuff I haven't caught yet). Also, we should type the `onChange` with a proper editor state

https://github.com/pubpub/platform/blob/01a9fc63fc654abb9a0b1b693e801cac4e0105ab/packages/context-editor/src/ContextEditor.tsx#L25-L37

**Comment by allisonking** [comment] 2024-10-23 21:21
A few notes as I'm bringing this into the app:

* need a way to set the editor as `disabled`
* would be nice to be able to pass a `className` down 

here's where I'm leaving off today, will likely need some help tomorrow!
https://github.com/pubpub/platform/pull/732

I had trouble getting react testing library to type in the editor field, so I'm thinking a playwright test might make more sense in lieu of a unit test

**Comment by allisonking** [comment] 2024-11-07 22:08
this is pretty much done, just pending some issues pre-merge (not sure if we want to merge yet, see https://github.com/pubpub/platform/pull/732#issuecomment-2463326624)

**Closed** 2024-11-18 20:38 UTC
Labels: 1-day
