### ISSUE TITLE
String fields with textArea apperance appear as input

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#688] opened 2024-10-03 20:27 UTC
### What went wrong, step-by-step?

1. On a form, user wants a string field to have a textArea appearance.
2. User configures string field to have a textArea appearance & saves.
3. On form, the textbox appears as "input" instead. 

### What URL can we use to see the issue?

Unjournal

### Have any screenshots? (Attach them by dragging the image here)

![image (1)](https://github.com/user-attachments/assets/2a7d61b7-359f-4ad0-870a-7625bec0a036)
![image](https://github.com/user-attachments/assets/5df3b74b-2dbe-4108-8e4b-123c2ad99714)

### Who reported this? (If not you)
David/Unjournal

**Comment by kalilsn** [comment] 2024-10-03 20:36
This was a regression caused by a merge conflict issue in #626 but should have just been fixed by #678

**Closed** 2024-10-03 20:42 UTC
Labels: bug
